apiVersion: k8soperator.sagar.com/v1
kind: Demo
metadata:
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: demo-sample
    app.kubernetes.io/part-of: k8soperator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8soperator
  name: demo-sample
spec:
  # TODO(user): Add fields here
  companyName: demo
  applicationDescription: testing
  appContainerName: sagar
  appImage: sagar27/petclinic-demo
  appPort: 8080
  monitorContainerName: monitor-container
  monitorImage: busybox:latest
  monitorCommand: "sh -c 'while true; do wget -O /dev/null  http://localhost:5001; sleep 10; done'"
  size: 3
  service:
    name: http
    namespace: default
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
    type: NodePort